### ISSUE TITLE
kingpin 080715a.vbs

### ISSUE THREAD

**Issue by Wob76** [sverrewl/vpxtable_scripts#24]
You are using a different version of the table to me, you have set useSolenoid=2 and its missing vpmInit Me, but being this is a capcom table it is unlikely to work without extensive script updates. I would test your version further.

**Comment by sverrewl** [comment]
That is a good point and I remember thinking just the same. Add or not. I guess the best solution right now would be to revert. I'm not the guy to solve such a problem if there is one.

**Comment by Wob76** [comment]
Yeah, I would revert to stock and leave it for a table upgrade, Rob Had a crack at Big Bang Bar but the table seems to lose track of balls in play so has some "odd behaviour" It could have been an issue prior to Fast Flips as I haven't played it enough.

**Comment by sverrewl** [comment]
Agreed. Reverted - thank you for all the help you've provided. Great work !!
